### PR TITLE
Change test file extension from 'eslint-test' to 'lint-test'

### PR DESCRIPTION
**Pull request by mitchlloyd**
This brings this library in line with the recent changes to ember-cli-qunit

### CODE REVIEW

**Comment by rwjblue** [comment]
Not to nit-pick, but can you tweak the commit message?

> ember-cli-qunit will not filter out '.lint-test.js' test files as well as '.jshint' files.

I think you meant "will **now** filter out", right?

**Comment by rwjblue** [comment]
This looks good except for that silly nit-pick.

**Comment by mitchlloyd** [comment]
One char change can mean so much.

**Comment by rwjblue** [comment]
LOL, yes indeed.

**Pull request merged**
