### PR TITLE
Upgrade to eslint@2.2.0

### PR DESCRIPTION
**Pull request by ehntoo**
https://github.com/jonathanKingston/broccoli-lint-eslint/issues/8

This is a bit messier than I'd like, as the upstream `nightmare-mode` eshint configs are designed for pre-2 eslint.

I'm also not quite sure how to test this standalone beyond the tests run by `npm test`, as I'm primarily an ember-cli user.

### CODE REVIEW

**Comment by chriskrycho** [comment]
@jonathanKingston, I'm happy to chip in and support @ehntoo's work here; we're blocked by this for our own work, so let me know what if anything needs doing so we can get this merged. :smile:

**Comment by jonathanKingston** [comment]
Let me fix nightmare-mode first then lets compare. Thanks for your work guys!

**Comment by chriskrycho** [comment]
@jonathanKingston Anything we can do to help get https://github.com/jonathanKingston/eslint-config-nightmare-mode where it needs to be? Happy to chip in some cycles to that end.

**Comment by jonathanKingston** [comment]
@chriskrycho I started the work here: https://github.com/jonathanKingston/eslint-config-nightmare-mode/tree/eslint/2.2.0
The tests are failing but everything else seems to be there mostly.

**Comment by chriskrycho** [comment]
I’ll see if I can get the tests passing this morning!

**Comment by chriskrycho** [comment]
[Should be unblocked shortly!](https://github.com/jonathanKingston/eslint-config-nightmare-mode/pull/3)

**Comment by jonathanKingston** [comment]
@chriskrycho the version of nightmare-mode is @2.2.0. Thanks

**Pull request closed without merging**
